### ISSUE TITLE
Pub package

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [escamoteur/web_gpu#2]
I think the plugin should be published to https://pub.dev 🙂

It seems like it is missing some basic setup (like properly filling in the `pubspec` properties), however, there are a few benefits to publishing it as a package:

* Easy use in Flutter apps (`git` dependencies do not work that well).
* Automatically generated API reference.
* Already being set up to be a proper plugin 🚀
* Reserves the name on Pub.

(I am aware that this is a stub repo for now - setting it up is beneficial nonetheless)

**Comment by escamoteur** [comment]
Oh, that is defentively the goal. This is a very raw sceletton of a plugin

**Comment by escamoteur** [comment]
Yeah, reserving the name is a good point

**Comment by creativecreatorormaybenot** [comment]
@escamoteur You can even publish a `0.0.0` version if you like 🙂

**Comment by escamoteur** [comment]
:-)

**Comment by escamoteur** [comment]
just pushed v 0.0.0 to reserve the name

**Comment by creativecreatorormaybenot** [comment]
@escamoteur Nice 👌 

Opened another PR for adding a badge: #11.
